// keep in sync with potato_aar::armaEvents
#define EVENT_OBJECT_CREATED 1
#define EVENT_OBJECT_KILLED 2
#define EVENT_FIRED 3
#define EVENT_MARKER_CREATED 4
#define EVENT_MARKER_DESTROYED 5
#define EVENT_MARKER_UPDATED 6
#define EVENT_OBJECT_GET_IN 7
#define EVENT_OBJECT_GET_OUT 8
#define EVENT_CUSTOM 9
#define EVENT_MISSION_START 10
#define EVENT_MISSION_END 11
